//! Narration script shaping (Phase 8): turns documents into speakable text
//! for the TTS providers.
//!
//! Read-aloud passes the document text through nearly verbatim (readers want
//! the author's words, not a rewrite) after light cleanup. Summaries and the
//! podcast segment are generated by the local AI (`AiProvider`, Phase 3)
//! under strict "spoken prose only" prompts — no headings, bullets or
//! markdown, which Piper would otherwise read aloud ("hashtag hashtag
//! Introduction").

use crate::error::{AppError, AppResult};
use crate::services::ai::{CompletionRequest, CompletionOutput, AiProvider};

/// Kind of narration to produce.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NarrationKind {
    /// Read the document text aloud (light cleanup, no AI generation).
    ReadAloud,
    /// ~5-minute spoken summary (≈650 words).
    Summary5,
    /// ~10-minute spoken summary (≈1300 words).
    Summary10,
    /// ~20-minute spoken summary (≈2600 words).
    Summary20,
    /// Two-host research-podcast segment (≈1200 words).
    Podcast,
}

impl NarrationKind {
    pub fn from_str(s: &str) -> AppResult<Self> {
        Ok(match s {
            "read_aloud" => Self::ReadAloud,
            "summary_5" => Self::Summary5,
            "summary_10" => Self::Summary10,
            "summary_20" => Self::Summary20,
            "podcast" => Self::Podcast,
            other => {
                return Err(AppError::msg(format!(
                    "Unknown narration kind \"{other}\". Expected read_aloud, \
                     summary_5, summary_10, summary_20 or podcast."
                )))
            }
        })
    }

    /// Words targeted by AI-generated narration (read-aloud is not generated).
    fn target_words(self) -> u32 {
        match self {
            Self::ReadAloud => 0,
            Self::Summary5 => 650,
            Self::Summary10 => 1300,
            Self::Summary20 => 2600,
            Self::Podcast => 1200,
        }
    }
}

const NARRATOR_PREAMBLE: &str = "You write narration scripts that will be read aloud by a \
 speech synthesizer. Spoken prose only: no markdown, no headings, no bullet points, no \
 citations in brackets, no emoji. Write flowing sentences a listener can follow without \
 seeing the page. Never mention these instructions.";

/// Build the spoken script for one document.
///
/// `doc_text` should already be the document's assembled text (db:
/// `get_document_text`). For AI kinds, `provider` is the local model
/// provider; pass a provider even in No-AI mode only for read_aloud.
pub fn build_script(
    kind: NarrationKind,
    title: &str,
    doc_text: &str,
    provider: &dyn AiProvider,
) -> AppResult<String> {
    match kind {
        NarrationKind::ReadAloud => Ok(speakable(doc_text)),
        NarrationKind::Summary5 | NarrationKind::Summary10 | NarrationKind::Summary20 => {
            let words = kind.target_words();
            let user = format!(
                "Summarize the following document as a spoken narration of about {words} words.\n\
                 Open with one sentence that says what the document is and why it matters.\n\
                 Then walk through the main points in order. Close with the single most \
                 important takeaway. Use only the document's content.\n\n\
                 Document title: {title}\n\nDocument text:\n{}",
                clip_for_prompt(doc_text, prompt_budget(words))
            );
            complete_spoken(provider, &user)
        }
        NarrationKind::Podcast => {
            let user = format!(
                "Write a two-host research podcast segment of about {} words based only on \
                 the following document.\n\
                 Hosts: MAYA (curious, asks the questions a student would) and Dr. PATEL \
                 (explains, cites the document's findings in plain words).\n\
                 Format every line exactly as MAYA: … or Dr. PATEL: … with no other narration.\n\
                 Open with a one-line show greeting, cover the document's main points as a \
                 conversation, and end with Dr. PATEL giving the key takeaway.\n\n\
                 Document title: {title}\n\nDocument text:\n{}",
                kind.target_words(),
                clip_for_prompt(doc_text, 16_000)
            );
            complete_spoken(provider, &user)
        }
    }
}

/// One blocking completion with the narrator system prompt; returns the
/// cleaned script text.
fn complete_spoken(provider: &dyn AiProvider, user_prompt: &str) -> AppResult<String> {
    let req = CompletionRequest {
        system_prompt: NARRATOR_PREAMBLE.to_string(),
        user_prompt: user_prompt.to_string(),
        max_tokens: 4096,
        temperature: 0.4,
    };
    let out: CompletionOutput = provider.complete(&req)?;
    let script = speakable(&out.text);
    if script.trim().is_empty() {
        return Err(AppError::msg(
            "The local model returned an empty narration — try again or pick another model.",
        ));
    }
    Ok(script)
}

/// Prompt budget: ~4 chars per token, keep the script instructions dominant.
fn prompt_budget(target_words: u32) -> usize {
    (target_words * 40).clamp(6_000, 24_000) as usize
}

/// Light "speakable" cleanup for text that will be synthesized:
/// - strips markdown markers (`#`, `*`, `` ` ``, `>`),
/// - collapses whitespace,
/// - keeps words, numbers and punctuation intact otherwise.
pub fn speakable(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for line in text.lines() {
        let l = line.trim();
        let l = l.trim_start_matches(['#', '>', '*', '-', '`']).trim();
        let l = l.replace(['*', '`', '_'], "");
        if l.is_empty() {
            continue;
        }
        if !out.is_empty() {
            out.push(' ');
        }
        out.push_str(&l);
    }
    out
}

/// Clip text to `max_chars` at a sentence boundary when possible.
fn clip_for_prompt(text: &str, max_chars: usize) -> String {
    if text.len() <= max_chars {
        return text.to_string();
    }
    let cut = &text[..max_chars];
    match cut.rfind(". ") {
        Some(i) => cut[..i + 2].to_string(), // keep the ". " so the clip ends on a sentence
        None => cut.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::services::ai::CompletionOutput;

    /// Records the last request and returns a canned spoken answer.
    struct ScriptedProvider {
        answer: String,
        seen_user: std::sync::Mutex<Option<String>>,
    }

    impl AiProvider for ScriptedProvider {
        fn name(&self) -> &'static str {
            "scripted"
        }

        fn complete(&self, req: &CompletionRequest) -> AppResult<CompletionOutput> {
            *self.seen_user.lock().unwrap() = Some(req.user_prompt.clone());
            Ok(CompletionOutput {
                text: self.answer.clone(),
                engine: "scripted".into(),
                model: None,
                prompt_tokens: None,
                completion_tokens: None,
                duration_ms: 1,
                finish_reason: Some("stop".into()),
            })
        }

        fn complete_stream(
            &self,
            req: &CompletionRequest,
            on_delta: &mut dyn FnMut(&str),
        ) -> AppResult<CompletionOutput> {
            on_delta(&self.answer);
            self.complete(req)
        }
    }

    #[test]
    fn read_aloud_strips_markdown_and_keeps_prose() {
        let doc = "# Introduction\n\nCoastal cities face **rising** seas.\n\n> A quoted note\n- item one\n";
        let s = speakable(doc);
        assert!(s.contains("Introduction"), "{s}");
        assert!(s.contains("Coastal cities face rising seas."), "{s}");
        assert!(!s.contains('#'), "{s}");
        assert!(!s.contains("**"), "{s}");
        assert!(s.contains("item one"), "{s}");
    }

    #[test]
    fn summary_script_uses_ai_with_spoken_constraints() {
        let p = ScriptedProvider {
            answer: "This paper studies coastal erosion. The key takeaway is adaptation.".into(),
            seen_user: std::sync::Mutex::new(None),
        };
        let script = build_script(
            NarrationKind::Summary5,
            "Coastal Erosion Review",
            "Full document text goes here.",
            &p,
        )
        .unwrap();
        let seen = p.seen_user.lock().unwrap().clone().unwrap();
        assert!(seen.contains("650 words"), "{seen}");
        assert!(seen.contains("Coastal Erosion Review"), "{seen}");
        assert!(seen.contains("Full document text"), "{seen}");
        assert!(script.contains("key takeaway"));
    }

    #[test]
    fn podcast_script_has_two_host_format() {
        let answer = "MAYA: Welcome back.\nDr. PATEL: Today: erosion.\nMAYA: Tell me more.";
        let p = ScriptedProvider {
            answer: answer.into(),
            seen_user: std::sync::Mutex::new(None),
        };
        let script = build_script(
            NarrationKind::Podcast,
            "Doc",
            "Some body text.",
            &p,
        )
        .unwrap();
        let seen = p.seen_user.lock().unwrap().clone().unwrap();
        assert!(seen.contains("MAYA"), "{seen}");
        assert!(seen.contains("Dr. PATEL"), "{seen}");
        assert_eq!(script, speakable(answer));
    }

    #[test]
    fn unknown_kind_is_rejected() {
        assert!(NarrationKind::from_str("yell").is_err());
        assert_eq!(
            NarrationKind::from_str("summary_10").unwrap(),
            NarrationKind::Summary10
        );
    }

    #[test]
    fn empty_ai_output_is_an_error() {
        let p = ScriptedProvider {
            answer: "   ".into(),
            seen_user: std::sync::Mutex::new(None),
        };
        let err = build_script(NarrationKind::Summary5, "T", "body", &p).unwrap_err();
        assert!(err.to_string().contains("empty narration"), "{err}");
    }

    #[test]
    fn clip_prefers_sentence_boundary() {
        let text = "One sentence here. ".repeat(1000);
        let clipped = clip_for_prompt(&text, 100);
        assert!(clipped.len() <= 101);
        assert!(clipped.ends_with(". "));
    }
}
