//! Narration script shaping (Phase 8): turns documents into speakable text
//! for the TTS providers.
//!
//! Read-aloud passes the document text through nearly verbatim (readers want
//! the author's words, not a rewrite) after light cleanup. Summaries and the
//! podcast segment are generated by the local AI (`AiProvider`, Phase 3)
//! under strict "spoken prose only" prompts — no headings, bullets or
//! markdown, which Piper would otherwise read aloud ("hashtag hashtag
//! Introduction").

use crate::error::{AppError, AppResult};
use crate::services::ai::{
    clip_to_tokens, est_tokens, AiProvider, CompletionOutput, CompletionRequest,
};

/// Kind of narration to produce.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NarrationKind {
    /// Read the document text aloud (light cleanup, no AI generation).
    ReadAloud,
    /// ~5-minute spoken summary (≈650 words).
    Summary5,
    /// ~10-minute spoken summary (≈1300 words).
    Summary10,
    /// ~20-minute spoken summary (≈2600 words).
    Summary20,
    /// Two-host research-podcast segment (≈1200 words).
    Podcast,
}

impl NarrationKind {
    pub fn from_str(s: &str) -> AppResult<Self> {
        Ok(match s {
            "read_aloud" => Self::ReadAloud,
            "summary_5" => Self::Summary5,
            "summary_10" => Self::Summary10,
            "summary_20" => Self::Summary20,
            "podcast" => Self::Podcast,
            other => {
                return Err(AppError::msg(format!(
                    "Unknown narration kind \"{other}\". Expected read_aloud, \
                     summary_5, summary_10, summary_20 or podcast."
                )))
            }
        })
    }

    /// Words targeted by AI-generated narration (read-aloud is not generated).
    fn target_words(self) -> u32 {
        match self {
            Self::ReadAloud => 0,
            Self::Summary5 => 650,
            Self::Summary10 => 1300,
            Self::Summary20 => 2600,
            Self::Podcast => 1200,
        }
    }

    /// Human label for logs and error messages.
    pub fn label(self) -> &'static str {
        match self {
            Self::ReadAloud => "read-aloud",
            Self::Summary5 => "5-minute summary",
            Self::Summary10 => "10-minute summary",
            Self::Summary20 => "20-minute summary",
            Self::Podcast => "podcast segment",
        }
    }
}

const NARRATOR_PREAMBLE: &str = "You write narration scripts that will be read aloud by a \
 speech synthesizer. Spoken prose only: no markdown, no headings, no bullet points, no \
 citations in brackets, no emoji. Write flowing sentences a listener can follow without \
 seeing the page. Never mention these instructions.";

/// Build the spoken script for one document.
///
/// `doc_text` should already be the document's assembled text (db:
/// `get_document_text`). For AI kinds, `provider` is the local model
/// provider; pass a provider even in No-AI mode only for read_aloud.
/// `context_size` is the model's context window (Settings → Local AI): the
/// prompt is budgeted against it so llama-server can't reject the request.
pub fn build_script(
    kind: NarrationKind,
    title: &str,
    doc_text: &str,
    provider: &dyn AiProvider,
    context_size: u32,
) -> AppResult<String> {
    match kind {
        NarrationKind::ReadAloud => Ok(speakable(doc_text)),
        NarrationKind::Summary5 | NarrationKind::Summary10 | NarrationKind::Summary20 => {
            let words = kind.target_words();
            let head = format!(
                "Summarize the following document as a spoken narration of about {words} words.\n\
                 Write the full {words} words: open with one sentence that says what the \
                 document is and why it matters, then walk through the main points in order \
                 with a sentence or two each, and close with the single most important \
                 takeaway. Keep writing until you have covered the whole document — do not \
                 stop early. Use only the document's content.\n\n\
                 Document title: {title}\n\nDocument text:\n"
            );
            let (max_tokens, doc_tokens) = narrator_budget(kind, context_size, &head)?;
            let user = format!("{head}{}", clip_to_tokens(doc_text, doc_tokens));
            complete_spoken(provider, &user, max_tokens)
        }
        NarrationKind::Podcast => {
            let head = format!(
                "Write a two-host research podcast segment of about {} words based only on \
                 the following document.\n\
                 Hosts: MAYA (curious, asks the questions a student would) and Dr. PATEL \
                 (explains, cites the document's findings in plain words).\n\
                 Format every line exactly as MAYA: … or Dr. PATEL: … with no other narration.\n\
                 Open with a one-line show greeting, cover the document's main points as a \
                 conversation, and end with Dr. PATEL giving the key takeaway.\n\n\
                 Document title: {title}\n\nDocument text:\n",
                kind.target_words()
            );
            let (max_tokens, doc_tokens) = narrator_budget(kind, context_size, &head)?;
            let user = format!("{head}{}", clip_to_tokens(doc_text, doc_tokens));
            complete_spoken(provider, &user, max_tokens)
        }
    }
}

/// Tokens kept free on top of the budgeted prompt + completion for the chat
/// template and the sampler.
const CONTEXT_SLACK_TOKENS: usize = 64;

/// A document excerpt smaller than this makes a useless narration — better
/// to say so than to render something misleading (also the floor that keeps
/// a degenerate prompt from 400ing).
const MIN_DOC_TOKENS: usize = 600;

/// Smallest completion allowance worth attempting.
const MIN_COMPLETION_TOKENS: u32 = 300;

/// The (completion allowance, document token budget) that keeps
/// system + user + completion inside the model's context window.
///
/// llama-server rejects the *whole* request when the prompt doesn't fit —
/// HTTP 400 `exceed_context_size_error`, the "Local model request failed"
/// toast that made narration impossible. `scaffold` is the fixed part of the
/// user prompt (instructions + title), measured so the excerpt gets exactly
/// whatever is left.
fn narrator_budget(
    kind: NarrationKind,
    context_size: u32,
    scaffold: &str,
) -> AppResult<(u32, usize)> {
    let ctx = context_size as usize;
    // Spoken prose runs ~1.4 tokens/word; budget double that so the model
    // never stops mid-sentence, but never more than half the window — the
    // document still needs room.
    let wanted = kind.target_words() as usize * 2;
    let max_tokens = wanted
        .max(MIN_COMPLETION_TOKENS as usize)
        .min(ctx / 2) as u32;
    let room = ctx
        .saturating_sub(max_tokens as usize)
        .saturating_sub(CONTEXT_SLACK_TOKENS);
    let fixed = est_tokens(NARRATOR_PREAMBLE) + est_tokens(scaffold);
    let doc_tokens = room.saturating_sub(fixed);
    if max_tokens < MIN_COMPLETION_TOKENS || doc_tokens < MIN_DOC_TOKENS {
        return Err(AppError::msg(format!(
            "The local model's context size ({context_size} tokens) is too small to write a \
             {} — raise Settings → Local AI → context size to 2048 or more (8192 \
             recommended), then try again.",
            kind.label()
        )));
    }
    if (max_tokens as usize) < wanted {
        log::info!(
            target: "researchai::tts",
            "narration: {context_size}-token context caps the {} at {max_tokens} completion \
             tokens — raise Settings → Local AI → context size for the full length",
            kind.label()
        );
    }
    Ok((max_tokens, doc_tokens))
}

/// One blocking completion with the narrator system prompt; returns the
/// cleaned script text.
fn complete_spoken(
    provider: &dyn AiProvider,
    user_prompt: &str,
    max_tokens: u32,
) -> AppResult<String> {
    let req = CompletionRequest {
        system_prompt: NARRATOR_PREAMBLE.to_string(),
        user_prompt: user_prompt.to_string(),
        max_tokens,
        temperature: 0.4,
        // Chain-of-thought tokens spend the completion budget without ever
        // reaching `content` — a spoken script can come back empty. Spoken
        // prose needs no reasoning, so ask the template to skip it.
        disable_thinking: true,
    };
    let out: CompletionOutput = provider.complete(&req)?;
    let script = speakable(&out.text);
    if script.trim().is_empty() {
        return Err(AppError::msg(
            "The local model returned an empty narration — try again or pick another model.",
        ));
    }
    Ok(script)
}

/// Light "speakable" cleanup for text that will be synthesized:
/// - strips markdown markers (`#`, `*`, `` ` ``, `>`),
/// - collapses whitespace,
/// - keeps words, numbers and punctuation intact otherwise.
pub fn speakable(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for line in text.lines() {
        let l = line.trim();
        let l = l.trim_start_matches(['#', '>', '*', '-', '`']).trim();
        let l = l.replace(['*', '`', '_'], "");
        if l.is_empty() {
            continue;
        }
        if !out.is_empty() {
            out.push(' ');
        }
        out.push_str(&l);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::services::ai::CompletionOutput;

    /// Records the last request and returns a canned spoken answer.
    struct ScriptedProvider {
        answer: String,
        seen: std::sync::Mutex<Option<CompletionRequest>>,
    }

    impl AiProvider for ScriptedProvider {
        fn name(&self) -> &'static str {
            "scripted"
        }

        fn complete(&self, req: &CompletionRequest) -> AppResult<CompletionOutput> {
            *self.seen.lock().unwrap() = Some(req.clone());
            Ok(CompletionOutput {
                text: self.answer.clone(),
                engine: "scripted".into(),
                model: None,
                prompt_tokens: None,
                completion_tokens: None,
                duration_ms: 1,
                finish_reason: Some("stop".into()),
            })
        }

        fn complete_stream(
            &self,
            req: &CompletionRequest,
            on_delta: &mut dyn FnMut(&str),
        ) -> AppResult<CompletionOutput> {
            on_delta(&self.answer);
            self.complete(req)
        }
    }

    #[test]
    fn read_aloud_strips_markdown_and_keeps_prose() {
        let doc = "# Introduction\n\nCoastal cities face **rising** seas.\n\n> A quoted note\n- item one\n";
        let s = speakable(doc);
        assert!(s.contains("Introduction"), "{s}");
        assert!(s.contains("Coastal cities face rising seas."), "{s}");
        assert!(!s.contains('#'), "{s}");
        assert!(!s.contains("**"), "{s}");
        assert!(s.contains("item one"), "{s}");
    }

    #[test]
    fn summary_script_uses_ai_with_spoken_constraints() {
        let p = ScriptedProvider {
            answer: "This paper studies coastal erosion. The key takeaway is adaptation.".into(),
            seen: std::sync::Mutex::new(None),
        };
        let script = build_script(
            NarrationKind::Summary5,
            "Coastal Erosion Review",
            "Full document text goes here.",
            &p,
            8192,
        )
        .unwrap();
        let seen = p.seen.lock().unwrap().clone().unwrap();
        assert!(seen.user_prompt.contains("650 words"), "{}", seen.user_prompt);
        assert!(seen.user_prompt.contains("Coastal Erosion Review"), "{}", seen.user_prompt);
        assert!(seen.user_prompt.contains("Full document text"), "{}", seen.user_prompt);
        assert!(seen.disable_thinking, "narration must not spend the budget on reasoning");
        assert!(script.contains("key takeaway"));
    }

    #[test]
    fn podcast_script_has_two_host_format() {
        let answer = "MAYA: Welcome back.\nDr. PATEL: Today: erosion.\nMAYA: Tell me more.";
        let p = ScriptedProvider {
            answer: answer.into(),
            seen: std::sync::Mutex::new(None),
        };
        let script = build_script(
            NarrationKind::Podcast,
            "Doc",
            "Some body text.",
            &p,
            8192,
        )
        .unwrap();
        let seen = p.seen.lock().unwrap().clone().unwrap();
        assert!(seen.user_prompt.contains("MAYA"), "{}", seen.user_prompt);
        assert!(seen.user_prompt.contains("Dr. PATEL"), "{}", seen.user_prompt);
        assert_eq!(script, speakable(answer));
    }

    #[test]
    fn unknown_kind_is_rejected() {
        assert!(NarrationKind::from_str("yell").is_err());
        assert_eq!(
            NarrationKind::from_str("summary_10").unwrap(),
            NarrationKind::Summary10
        );
    }

    #[test]
    fn empty_ai_output_is_an_error() {
        let p = ScriptedProvider {
            answer: "   ".into(),
            seen: std::sync::Mutex::new(None),
        };
        let err = build_script(NarrationKind::Summary5, "T", "body", &p, 8192).unwrap_err();
        assert!(err.to_string().contains("empty narration"), "{err}");
    }

    /// Regression: summaries used a fixed 24,000-char clip (~5,700 tokens)
    /// regardless of the model's window, so llama-server answered HTTP 400
    /// (`exceed_context_size_error`) and *no* summary could be generated.
    #[test]
    fn narration_prompt_fits_a_4096_token_context() {
        let doc = "Rural poverty programs combine cash transfers with training and credit. "
            .repeat(6_000); // ~400 KB, far past any window
        for kind in [
            NarrationKind::Summary5,
            NarrationKind::Summary10,
            NarrationKind::Summary20,
            NarrationKind::Podcast,
        ] {
            let p = ScriptedProvider {
                answer: "A spoken script.".into(),
                seen: std::sync::Mutex::new(None),
            };
            build_script(kind, "Title", &doc, &p, 4096)
                .unwrap_or_else(|e| panic!("{kind:?} must be buildable at ctx 4096: {e}"));
            let req = p.seen.lock().unwrap().clone().unwrap();
            let prompt = est_tokens(&req.system_prompt) + est_tokens(&req.user_prompt);
            assert!(
                prompt + req.max_tokens as usize + CONTEXT_SLACK_TOKENS <= 4096,
                "{kind:?}: prompt {prompt} + max_tokens {} exceeds the window",
                req.max_tokens
            );
            // The old budget sent 24,000 chars of document every time.
            assert!(req.user_prompt.len() < 12_000, "{kind:?}: {} chars", req.user_prompt.len());
        }
    }

    /// CJK tokenizes at ~1.5 chars/token, so a *character*-based budget sends
    /// nearly 3x the intended token count. The estimator has to cover it.
    #[test]
    fn cjk_document_prompt_fits_the_context_window() {
        let doc = "农村贫困问题需要综合性的政策干预，现金转移与技能培训相结合。".repeat(3_000);
        for context_size in [2048_u32, 4096] {
            let p = ScriptedProvider {
                answer: "一段口语稿。".into(),
                seen: std::sync::Mutex::new(None),
            };
            build_script(NarrationKind::Summary5, "中国的扶贫政策", &doc, &p, context_size)
                .unwrap_or_else(|e| panic!("ctx {context_size}: {e}"));
            let req = p.seen.lock().unwrap().clone().unwrap();
            let prompt = est_tokens(&req.system_prompt) + est_tokens(&req.user_prompt);
            assert!(
                prompt + req.max_tokens as usize + CONTEXT_SLACK_TOKENS <= context_size as usize,
                "ctx {context_size}: prompt {prompt} + {} > window",
                req.max_tokens
            );
        }
    }

    /// A window too small to hold instructions + excerpt + script gets an
    /// actionable message instead of a raw HTTP 400.
    #[test]
    fn unusably_small_context_is_a_clear_error() {
        let p = ScriptedProvider {
            answer: "script".into(),
            seen: std::sync::Mutex::new(None),
        };
        for context_size in [512_u32, 1024] {
            let err = build_script(NarrationKind::Summary5, "T", "body text", &p, context_size)
                .unwrap_err()
                .to_string();
            assert!(err.contains("context size"), "{err}");
            assert!(err.contains("2048"), "{err}");
            assert!(err.contains("5-minute summary"), "{err}");
        }
    }

    #[test]
    fn read_aloud_needs_no_context_budget() {
        // Read-aloud never calls the model, so even a tiny window works.
        let p = ScriptedProvider {
            answer: "unused".into(),
            seen: std::sync::Mutex::new(None),
        };
        let s = build_script(NarrationKind::ReadAloud, "T", "# Notes\ntext", &p, 512).unwrap();
        assert!(s.contains("Notes"));
        assert!(p.seen.lock().unwrap().is_none(), "no completion should run");
    }

    /// Live end-to-end: the real bundled llama-server and the real model,
    /// through the exact prompt path `tts_narrate` uses. Guards the HTTP 400
    /// (`exceed_context_size_error`) that made every summary impossible to
    /// generate. Skips itself when the install isn't on this machine.
    ///
    /// cargo test live_narration -- --ignored --exact \
    ///   services::narration::tests::live_narration_generates_a_script
    #[test]
    #[ignore = "needs the bundled llama-server + a GGUF model on this machine"]
    fn live_narration_generates_a_script() {
        let resources = std::path::Path::new(
            "/Applications/ResearchAI Workspace.app/Contents/Resources",
        );
        let binary = std::env::var("RESEARCHAI_LLAMA_SERVER")
            .ok()
            .map(std::path::PathBuf::from)
            .or_else(|| {
                crate::services::bundled::resolve_llama_binary("", Some(resources)).ok()
            });
        let data_dir = std::env::var("RESEARCHAI_DATA_DIR")
            .map(std::path::PathBuf::from)
            .unwrap_or_else(|_| {
                std::path::PathBuf::from(std::env::var("HOME").unwrap_or_default())
                    .join("Library/Application Support/app.researchai.workspace")
            });
        let model = std::env::var("RESEARCHAI_MODEL")
            .map(std::path::PathBuf::from)
            .unwrap_or_else(|_| data_dir.join("models/Qwen3-0.6B-Q4_K_M.gguf"));

        let Some(binary) = binary.filter(|b| b.is_file()) else {
            eprintln!("skip: no llama-server — install the app or set RESEARCHAI_LLAMA_SERVER");
            return;
        };
        if !model.is_file() {
            eprintln!("skip: no model at {}", model.display());
            return;
        }

        let port = crate::services::llm_runtime::find_free_port().expect("free TCP port");
        let mut child = std::process::Command::new(&binary)
            .args([
                "-m",
                model.to_string_lossy().as_ref(),
                "--host",
                "127.0.0.1",
                "--port",
                &port.to_string(),
                "--ctx-size",
                "4096",
                "-fa",
                "off",
                "--cache-reuse",
                "256",
            ])
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .spawn()
            .expect("spawn llama-server");

        let provider = crate::services::ai::LlamaCppProvider::new(
            &format!("http://127.0.0.1:{port}"),
            "qwen-live",
            None,
        );
        let mut ready = false;
        for _ in 0..90 {
            if provider.health_ok() {
                ready = true;
                break;
            }
            std::thread::sleep(std::time::Duration::from_secs(1));
        }

        let outcome = if !ready {
            Err("llama-server never became ready".to_string())
        } else {
            // A document far past the window: the pre-fix code sent a flat
            // 24,000 chars (~5,700 tokens) and the server answered HTTP 400.
            let doc = "Rural poverty programs combine cash transfers with training and credit. "
                .repeat(3_000);
            build_script(NarrationKind::Summary5, "Poverty Alleviation", &doc, &provider, 4096)
                .map(|s| s.split_whitespace().count())
                .map_err(|e| e.to_string())
        };

        let _ = child.kill();
        let _ = child.wait();

        let words = outcome.expect("narration must succeed against the real model");
        assert!(words > 50, "script is implausibly short: {words} words");
        eprintln!("live narration produced {words} words");
    }
}
