//! Text-to-speech commands (Phase 8, spec §21, §47.7): TTS settings,
//! availability probe and narration jobs. Read-aloud works without AI;
//! summaries and the podcast segment are generated by the local model
//! (No-AI mode gates those, spec §35) and every result is a real audio
//! file rendered by the user-configured local voice.

use serde::Serialize;
use tauri::{AppHandle, Manager, State};

use crate::services::ai::AiProvider as _;
use crate::services::tts::TextToSpeechProvider as _;

use crate::error::{AppError, AppResult};
use crate::state::AppState;

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TtsStatusResponse {
    /// Selected provider id ("piper" | "macos-say").
    pub provider: String,
    pub binary_found: bool,
    pub model_found: bool,
    pub ffmpeg_found: bool,
    pub ready: bool,
    pub output_dir: String,
    pub settings: crate::db::TtsSettings,
}

fn status_response(state: &AppState) -> AppResult<TtsStatusResponse> {
    let s = state.db.get_tts_settings()?;
    let out_dir = state.data_dir.join("exports");
    let (provider, effective) = effective_provider(&s, out_dir)?;
    let st = provider.check();
    Ok(TtsStatusResponse {
        provider: effective,
        binary_found: st.binary_found,
        model_found: st.model_found,
        ffmpeg_found: crate::services::transcription::ffmpeg_available(),
        ready: st.ready,
        output_dir: st.output_dir,
        settings: s,
    })
}

/// The provider that will actually render, plus its id (`"piper"` |
/// `"macos-say"`) for status and UI labels.
///
/// Normally this is the saved selection. When Piper is selected but not
/// usable — binary or voice model missing, the classic half-configured
/// install — the built-in macOS `say` voice takes over on macOS so audio
/// generation works with zero setup (spec §47.7 fallback voice). Status and
/// both render commands go through this one function, so what the UI reports
/// as ready is exactly what renders.
fn effective_provider(
    s: &crate::db::TtsSettings,
    out_dir: std::path::PathBuf,
) -> AppResult<(Box<dyn crate::services::tts::TextToSpeechProvider>, String)> {
    let selected = crate::services::tts::provider_for(s, out_dir.clone())?;
    if selected.check().ready {
        return Ok((selected, s.provider.clone()));
    }
    #[cfg(target_os = "macos")]
    if s.provider != "macos-say" {
        let say = crate::services::tts::MacOsSayProvider::from_settings(s, out_dir);
        if say.check().ready {
            log::info!(
                target: "researchai::tts",
                "piper selected but not ready — falling back to the built-in macOS say voice"
            );
            return Ok((Box::new(say), "macos-say".into()));
        }
    }
    Ok((selected, s.provider.clone()))
}

#[tauri::command]
pub fn tts_check(state: State<'_, AppState>) -> AppResult<TtsStatusResponse> {
    status_response(&state)
}

#[tauri::command]
pub fn tts_get_settings(state: State<'_, AppState>) -> AppResult<crate::db::TtsSettings> {
    state.db.get_tts_settings()
}

#[tauri::command]
pub fn tts_save_settings(
    state: State<'_, AppState>,
    settings: crate::db::TtsSettings,
) -> AppResult<crate::db::TtsSettings> {
    let s = prepare_tts_settings(settings)?;
    state.db.save_tts_settings(&s)?;
    Ok(s)
}

/// Normalize and validate saved TTS settings (kept free of Tauri state so
/// the guards above are unit-testable).
fn prepare_tts_settings(mut s: crate::db::TtsSettings) -> AppResult<crate::db::TtsSettings> {
    s.provider = if s.provider == "macos-say" {
        "macos-say".into()
    } else {
        "piper".into()
    };
    s.piper_path = s.piper_path.trim().to_string();
    s.voice_model_path = s.voice_model_path.trim().to_string();
    s.macos_voice = s.macos_voice.trim().to_string();
    s.speed = s.speed.clamp(0.5, 2.0);
    // Piper fields are only validated while Piper is the selected provider —
    // switching to the macOS voice must stay possible with stale paths set.
    if s.provider == "piper" {
        crate::services::path_validation::validate_binary_path(
            &s.piper_path,
            "piper",
            "install it (e.g. `brew install piper`) and point at the executable, e.g. \
             /opt/homebrew/bin/piper",
        )?;
        crate::services::path_validation::validate_model_path(
            &s.voice_model_path,
            "a Piper voice model",
            "onnx",
        )?;
    }
    Ok(s)
}

/// Result of one narration job (Phase 8).
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct NarrationResult {
    /// Absolute path of the rendered audio file.
    pub audio_path: String,
    /// "wav" or "mp3".
    pub format: String,
    pub bytes: u64,
    pub duration_ms: u64,
    /// Words in the spoken script.
    pub words: usize,
    /// Engine that generated the script ("read_aloud" | "llama.cpp" | …).
    pub engine: String,
}

impl NarrationResult {
    fn from_audio(
        audio: crate::services::tts::TtsAudio,
        words: usize,
        engine: String,
    ) -> Self {
        Self {
            audio_path: audio.path,
            format: audio.format,
            bytes: audio.bytes,
            duration_ms: audio.duration_ms,
            words,
            engine,
        }
    }
}

/// Speak a document aloud: reads the document's own text (light cleanup,
/// no AI). Works in No-AI mode.
#[tauri::command]
pub async fn tts_speak_document(
    app: AppHandle,
    document_id: String,
) -> AppResult<NarrationResult> {
    tauri::async_runtime::spawn_blocking(move || {
        let state = app.state::<AppState>();
        speak_document_inner(&state, &document_id)
    })
    .await
    .map_err(|e| AppError::msg(format!("Read-aloud failed to run: {e}")))?
}

fn speak_document_inner(state: &AppState, document_id: &str) -> AppResult<NarrationResult> {
    let s = state.db.get_tts_settings()?;
    let doc_text = state.db.get_document_text(document_id)?;
    if doc_text.trim().is_empty() {
        return Err(AppError::msg(
            "This document has no readable text yet — wait for indexing to finish.",
        ));
    }
    let title = state
        .db
        .get_document(document_id)
        .ok()
        .map(|d| d.title.unwrap_or_else(|| d.file_name))
        .unwrap_or_else(|| "document".into());

    let script = crate::services::narration::speakable(&doc_text);
    let words = script.split_whitespace().count();
    let hint = sanitize_hint(&title);
    let (voice, _) = effective_provider(&s, state.data_dir.join("exports"))?;
    let audio = voice.render(&script, &hint)?;
    Ok(NarrationResult::from_audio(audio, words, "read_aloud".into()))
}

/// Generate a spoken narration (summary or podcast) with the local model and
/// render it to audio. Hard-gated in No-AI mode (spec §35).
#[tauri::command]
pub async fn tts_narrate(
    app: AppHandle,
    document_id: String,
    kind: String,
) -> AppResult<NarrationResult> {
    tauri::async_runtime::spawn_blocking(move || {
        let state = app.state::<AppState>();

        if !state
            .settings
            .lock()
            .expect("settings lock")
            .ai_enabled
        {
            return Err(AppError::msg(
                "AI is disabled (No-AI mode). Summaries and podcast narration need the local \
                 model — read-aloud still works.",
            ));
        }

        let kind = crate::services::narration::NarrationKind::from_str(&kind)?;
        if matches!(kind, crate::services::narration::NarrationKind::ReadAloud) {
            return speak_document_inner(&state, &document_id);
        }

        // Script generation needs the local model: resolve + load on demand
        // (same flow as ai_ask, Phase 3).
        let ai = state.db.get_ai_settings()?;
        let model = resolve_model(&state.db, &ai)?;
        let binary = crate::services::bundled::resolve_llama_binary(
            &ai.llama_server_path,
            state.resource_dir.as_deref(),
        )?;
        if !matches!(
            state.llm_runtime.snapshot().state,
            crate::services::llm_runtime::LoadState::Ready { .. }
        ) {
            state.llm_runtime.ensure_loaded(
                &binary,
                std::path::Path::new(&model.file_path),
                &ai,
                std::time::Duration::from_secs(120),
            )?;
        }
        state.llm_runtime.touch();
        let snapshot = state.llm_runtime.snapshot();
        let port = match snapshot.state {
            crate::services::llm_runtime::LoadState::Ready { port } => port,
            crate::services::llm_runtime::LoadState::Failed { detail } => {
                return Err(AppError::msg(detail))
            }
            _ => return Err(AppError::msg("The local model is not ready yet.")),
        };
        let provider = crate::services::ai::LlamaCppProvider::new(
            &format!("http://127.0.0.1:{port}"),
            &model.file_name,
            None,
        );

        let doc_text = state.db.get_document_text(&document_id)?;
        if doc_text.trim().is_empty() {
            return Err(AppError::msg(
                "This document has no readable text yet — wait for indexing to finish.",
            ));
        }
        let title = state
            .db
            .get_document(&document_id)
            .ok()
            .map(|d| d.title.unwrap_or_else(|| d.file_name))
            .unwrap_or_else(|| "document".into());

        let script = crate::services::narration::build_script(kind, &title, &doc_text, &provider)?;
        let words = script.split_whitespace().count();
        let hint = sanitize_hint(&title);

        let tts = state.db.get_tts_settings()?;
        let (voice, _) = effective_provider(&tts, state.data_dir.join("exports"))?;
        let audio = voice.render(&script, &format!("{}-{hint}", kind_slug(kind)))?;
        Ok(NarrationResult::from_audio(
            audio,
            words,
            provider.name().to_string(),
        ))
    })
    .await
    .map_err(|e| AppError::msg(format!("Narration failed to run: {e}")))?
}

use crate::db::LocalModelRow;

fn resolve_model(db: &crate::db::Db, settings: &crate::db::AiSettings) -> AppResult<LocalModelRow> {
    let id = settings
        .active_model_id
        .as_deref()
        .ok_or_else(|| AppError::msg(
            "No local model is selected. Add a GGUF model in Settings → Local AI and choose one.",
        ))?;
    let model = db.get_local_model(id)?;
    if model.status != "available" {
        return Err(AppError::msg(format!(
            "The selected model file is not available on disk ({}). Re-scan or re-add it.",
            model.status
        )));
    }
    Ok(model)
}

fn sanitize_hint(title: &str) -> String {
    let cleaned: String = title
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect();
    let trimmed = cleaned.trim_matches('-').to_string();
    if trimmed.is_empty() {
        "doc".into()
    } else {
        trimmed.chars().take(40).collect()
    }
}

fn kind_slug(kind: crate::services::narration::NarrationKind) -> String {
    match kind {
        crate::services::narration::NarrationKind::ReadAloud => "read_aloud".into(),
        crate::services::narration::NarrationKind::Summary5 => "summary-5min".into(),
        crate::services::narration::NarrationKind::Summary10 => "summary-10min".into(),
        crate::services::narration::NarrationKind::Summary20 => "summary-20min".into(),
        crate::services::narration::NarrationKind::Podcast => "podcast".into(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A fully configured Piper (binary + voice present) must stay selected.
    #[cfg(unix)]
    #[test]
    fn configured_piper_stays_piper() {
        use std::os::unix::fs::PermissionsExt as _;

        let dir = crate::db::tests::TempDir::new_with_label("tts-eff");
        let bin = dir.path().join("piper");
        std::fs::write(&bin, b"#!/bin/sh\nexit 0\n").unwrap();
        std::fs::set_permissions(&bin, std::fs::Permissions::from_mode(0o755)).unwrap();
        let model = dir.path().join("en_US-amy-medium.onnx");
        std::fs::write(&model, b"onnx").unwrap();

        let s = crate::db::TtsSettings {
            provider: "piper".into(),
            piper_path: bin.to_string_lossy().into_owned(),
            voice_model_path: model.to_string_lossy().into_owned(),
            ..crate::db::TtsSettings::default()
        };
        let (prov, id) = effective_provider(&s, dir.path().join("out")).unwrap();
        assert_eq!(id, "piper");
        assert!(prov.check().ready);
    }

    /// Unconfigured Piper on macOS falls back to the zero-install `say`
    /// voice so "Render audio" works out of the box.
    #[cfg(target_os = "macos")]
    #[test]
    fn unconfigured_piper_falls_back_to_the_macos_voice() {
        let dir = crate::db::tests::TempDir::new_with_label("tts-fb");
        let s = crate::db::TtsSettings {
            provider: "piper".into(),
            ..crate::db::TtsSettings::default()
        };
        let (prov, id) = effective_provider(&s, dir.path().join("out")).unwrap();
        if id != "macos-say" {
            // `say` unavailable in this environment — nothing to assert.
            return;
        }
        assert!(prov.check().ready);
    }

    /// Saving a recording as the piper binary is rejected with guidance
    /// instead of silently disabling audio generation.
    #[test]
    fn saving_an_audio_file_as_the_piper_binary_is_rejected() {
        let err = prepare_tts_settings(crate::db::TtsSettings {
            provider: "piper".into(),
            piper_path: "/Users/odere/Downloads/take_I.wav".into(),
            ..crate::db::TtsSettings::default()
        })
        .unwrap_err()
        .to_string();
        assert!(err.contains("audio/video file"), "got: {err}");
        assert!(err.contains("piper"), "got: {err}");
    }

    /// The same settings save cleanly once Piper is deselected — switching
    /// to the macOS voice must never be blocked by stale Piper paths.
    #[test]
    fn macos_say_selection_skips_piper_path_validation() {
        let saved = prepare_tts_settings(crate::db::TtsSettings {
            provider: "macos-say".into(),
            piper_path: "/Users/odere/Downloads/take_I.wav".into(),
            ..crate::db::TtsSettings::default()
        })
        .unwrap();
        assert_eq!(saved.provider, "macos-say");
    }
}
