//! Text-to-speech commands (Phase 8, spec §21, §47.7): TTS settings,
//! availability probe and narration jobs. Read-aloud works without AI;
//! summaries and the podcast segment are generated by the local model
//! (No-AI mode gates those, spec §35) and every result is a real audio
//! file rendered by the user-configured local voice.

use serde::Serialize;
use tauri::{AppHandle, Manager, State};

use crate::services::ai::AiProvider as _;

use crate::error::{AppError, AppResult};
use crate::state::AppState;

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TtsStatusResponse {
    /// Selected provider id ("piper" | "macos-say").
    pub provider: String,
    pub binary_found: bool,
    pub model_found: bool,
    pub ffmpeg_found: bool,
    pub ready: bool,
    pub output_dir: String,
    pub settings: crate::db::TtsSettings,
}

fn status_response(state: &AppState) -> AppResult<TtsStatusResponse> {
    let s = state.db.get_tts_settings()?;
    let out_dir = state.data_dir.join("exports");
    let st = crate::services::tts::provider_for(&s, out_dir)?.check();
    Ok(TtsStatusResponse {
        provider: s.provider.clone(),
        binary_found: st.binary_found,
        model_found: st.model_found,
        ffmpeg_found: crate::services::transcription::ffmpeg_available(),
        ready: st.ready,
        output_dir: st.output_dir,
        settings: s,
    })
}

#[tauri::command]
pub fn tts_check(state: State<'_, AppState>) -> AppResult<TtsStatusResponse> {
    status_response(&state)
}

#[tauri::command]
pub fn tts_get_settings(state: State<'_, AppState>) -> AppResult<crate::db::TtsSettings> {
    state.db.get_tts_settings()
}

#[tauri::command]
pub fn tts_save_settings(
    state: State<'_, AppState>,
    settings: crate::db::TtsSettings,
) -> AppResult<crate::db::TtsSettings> {
    let mut s = settings;
    s.provider = if s.provider == "macos-say" {
        "macos-say".into()
    } else {
        "piper".into()
    };
    s.piper_path = s.piper_path.trim().to_string();
    s.voice_model_path = s.voice_model_path.trim().to_string();
    s.macos_voice = s.macos_voice.trim().to_string();
    s.speed = s.speed.clamp(0.5, 2.0);
    state.db.save_tts_settings(&s)?;
    Ok(s)
}

/// Result of one narration job (Phase 8).
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct NarrationResult {
    /// Absolute path of the rendered audio file.
    pub audio_path: String,
    /// "wav" or "mp3".
    pub format: String,
    pub bytes: u64,
    pub duration_ms: u64,
    /// Words in the spoken script.
    pub words: usize,
    /// Engine that generated the script ("read_aloud" | "llama.cpp" | …).
    pub engine: String,
}

impl NarrationResult {
    fn from_audio(
        audio: crate::services::tts::TtsAudio,
        words: usize,
        engine: String,
    ) -> Self {
        Self {
            audio_path: audio.path,
            format: audio.format,
            bytes: audio.bytes,
            duration_ms: audio.duration_ms,
            words,
            engine,
        }
    }
}

/// Speak a document aloud: reads the document's own text (light cleanup,
/// no AI). Works in No-AI mode.
#[tauri::command]
pub async fn tts_speak_document(
    app: AppHandle,
    document_id: String,
) -> AppResult<NarrationResult> {
    tauri::async_runtime::spawn_blocking(move || {
        let state = app.state::<AppState>();
        speak_document_inner(&state, &document_id)
    })
    .await
    .map_err(|e| AppError::msg(format!("Read-aloud failed to run: {e}")))?
}

fn speak_document_inner(state: &AppState, document_id: &str) -> AppResult<NarrationResult> {
    let s = state.db.get_tts_settings()?;
    let doc_text = state.db.get_document_text(document_id)?;
    if doc_text.trim().is_empty() {
        return Err(AppError::msg(
            "This document has no readable text yet — wait for indexing to finish.",
        ));
    }
    let title = state
        .db
        .get_document(document_id)
        .ok()
        .map(|d| d.title.unwrap_or_else(|| d.file_name))
        .unwrap_or_else(|| "document".into());

    let script = crate::services::narration::speakable(&doc_text);
    let words = script.split_whitespace().count();
    let hint = sanitize_hint(&title);
    let audio = crate::services::tts::provider_for(&s, state.data_dir.join("exports"))?
        .render(&script, &hint)?;
    Ok(NarrationResult::from_audio(audio, words, "read_aloud".into()))
}

/// Generate a spoken narration (summary or podcast) with the local model and
/// render it to audio. Hard-gated in No-AI mode (spec §35).
#[tauri::command]
pub async fn tts_narrate(
    app: AppHandle,
    document_id: String,
    kind: String,
) -> AppResult<NarrationResult> {
    tauri::async_runtime::spawn_blocking(move || {
        let state = app.state::<AppState>();

        if !state
            .settings
            .lock()
            .expect("settings lock")
            .ai_enabled
        {
            return Err(AppError::msg(
                "AI is disabled (No-AI mode). Summaries and podcast narration need the local \
                 model — read-aloud still works.",
            ));
        }

        let kind = crate::services::narration::NarrationKind::from_str(&kind)?;
        if matches!(kind, crate::services::narration::NarrationKind::ReadAloud) {
            return speak_document_inner(&state, &document_id);
        }

        // Script generation needs the local model: resolve + load on demand
        // (same flow as ai_ask, Phase 3).
        let ai = state.db.get_ai_settings()?;
        let model = resolve_model(&state.db, &ai)?;
        let binary = crate::services::bundled::resolve_llama_binary(
            &ai.llama_server_path,
            state.resource_dir.as_deref(),
        )?;
        if !matches!(
            state.llm_runtime.snapshot().state,
            crate::services::llm_runtime::LoadState::Ready { .. }
        ) {
            state.llm_runtime.ensure_loaded(
                &binary,
                std::path::Path::new(&model.file_path),
                &ai,
                std::time::Duration::from_secs(120),
            )?;
        }
        state.llm_runtime.touch();
        let snapshot = state.llm_runtime.snapshot();
        let port = match snapshot.state {
            crate::services::llm_runtime::LoadState::Ready { port } => port,
            crate::services::llm_runtime::LoadState::Failed { detail } => {
                return Err(AppError::msg(detail))
            }
            _ => return Err(AppError::msg("The local model is not ready yet.")),
        };
        let provider = crate::services::ai::LlamaCppProvider::new(
            &format!("http://127.0.0.1:{port}"),
            &model.file_name,
            None,
        );

        let doc_text = state.db.get_document_text(&document_id)?;
        if doc_text.trim().is_empty() {
            return Err(AppError::msg(
                "This document has no readable text yet — wait for indexing to finish.",
            ));
        }
        let title = state
            .db
            .get_document(&document_id)
            .ok()
            .map(|d| d.title.unwrap_or_else(|| d.file_name))
            .unwrap_or_else(|| "document".into());

        let script = crate::services::narration::build_script(kind, &title, &doc_text, &provider)?;
        let words = script.split_whitespace().count();
        let hint = sanitize_hint(&title);

        let tts = state.db.get_tts_settings()?;
        let audio = crate::services::tts::provider_for(&tts, state.data_dir.join("exports"))?
            .render(&script, &format!("{}-{hint}", kind_slug(kind)))?;
        Ok(NarrationResult::from_audio(
            audio,
            words,
            provider.name().to_string(),
        ))
    })
    .await
    .map_err(|e| AppError::msg(format!("Narration failed to run: {e}")))?
}

use crate::db::LocalModelRow;

fn resolve_model(db: &crate::db::Db, settings: &crate::db::AiSettings) -> AppResult<LocalModelRow> {
    let id = settings
        .active_model_id
        .as_deref()
        .ok_or_else(|| AppError::msg(
            "No local model is selected. Add a GGUF model in Settings → Local AI and choose one.",
        ))?;
    let model = db.get_local_model(id)?;
    if model.status != "available" {
        return Err(AppError::msg(format!(
            "The selected model file is not available on disk ({}). Re-scan or re-add it.",
            model.status
        )));
    }
    Ok(model)
}

fn sanitize_hint(title: &str) -> String {
    let cleaned: String = title
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect();
    let trimmed = cleaned.trim_matches('-').to_string();
    if trimmed.is_empty() {
        "doc".into()
    } else {
        trimmed.chars().take(40).collect()
    }
}

fn kind_slug(kind: crate::services::narration::NarrationKind) -> String {
    match kind {
        crate::services::narration::NarrationKind::ReadAloud => "read_aloud".into(),
        crate::services::narration::NarrationKind::Summary5 => "summary-5min".into(),
        crate::services::narration::NarrationKind::Summary10 => "summary-10min".into(),
        crate::services::narration::NarrationKind::Summary20 => "summary-20min".into(),
        crate::services::narration::NarrationKind::Podcast => "podcast".into(),
    }
}
