//! Text-to-speech commands (Phase 8, spec §21, §47.7): TTS settings,
//! availability probe and narration jobs. Read-aloud works without AI;
//! summaries and the podcast segment are generated by the local model
//! (No-AI mode gates those, spec §35) and every result is a real audio
//! file rendered by the user-configured local voice.

use serde::Serialize;
use tauri::{AppHandle, Manager, State};

use crate::services::ai::AiProvider as _;
use crate::services::tts::TextToSpeechProvider as _;

use crate::error::{AppError, AppResult};
use crate::state::AppState;

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TtsStatusResponse {
    /// Selected provider id ("piper" | "macos-say" | "master-voice").
    pub provider: String,
    pub binary_found: bool,
    pub model_found: bool,
    pub ffmpeg_found: bool,
    pub ready: bool,
    /// Master Voice only: F5-TTS checkpoint already cached (false = the
    /// first render downloads ~1.3 GB).
    pub master_assets_cached: bool,
    pub output_dir: String,
    pub settings: crate::db::TtsSettings,
}

fn status_response(state: &AppState) -> AppResult<TtsStatusResponse> {
    let s = state.db.get_tts_settings()?;
    let out_dir = state.data_dir.join("exports");
    let (provider, effective) = effective_provider(&s, state.resource_dir.as_deref(), out_dir)?;
    let st = provider.check();
    Ok(TtsStatusResponse {
        provider: effective,
        binary_found: st.binary_found,
        model_found: st.model_found,
        ffmpeg_found: crate::services::transcription::ffmpeg_available(),
        ready: st.ready,
        master_assets_cached: crate::services::master_voice::f5_assets_cached(),
        output_dir: st.output_dir,
        settings: s,
    })
}

/// The provider that will actually render, plus its id (`"piper"` |
/// `"macos-say"` | `"master-voice"`) for status and UI labels.
///
/// Normally this is the saved selection. When the saved provider is not
/// usable — the classic half-configured install (Piper without binary or
/// model, Master Voice without `uv` or recording) — a built-in fallback
/// takes over so audio generation still works: the macOS `say` voice on
/// macOS (zero setup), Piper when it is configured. Status and both render
/// commands go through this one function, so what the UI reports as ready
/// is exactly what renders.
fn effective_provider(
    s: &crate::db::TtsSettings,
    resource_dir: Option<&std::path::Path>,
    out_dir: std::path::PathBuf,
) -> AppResult<(Box<dyn crate::services::tts::TextToSpeechProvider>, String)> {
    let selected = crate::services::tts::provider_for(s, resource_dir, out_dir.clone())?;
    if selected.check().ready {
        return Ok((selected, s.provider.clone()));
    }
    if s.provider != "piper" {
        // Piper first when it is actually configured (works on every OS).
        let piper = crate::services::tts::PiperProvider::from_settings(s, out_dir.clone());
        if piper.check().ready {
            log::info!(
                target: "researchai::tts",
                "{} selected but not ready — falling back to Piper",
                s.provider
            );
            return Ok((Box::new(piper), "piper".into()));
        }
    }
    #[cfg(target_os = "macos")]
    if s.provider != "macos-say" {
        let say = crate::services::tts::MacOsSayProvider::from_settings(s, out_dir);
        if say.check().ready {
            log::info!(
                target: "researchai::tts",
                "{} selected but not ready — falling back to the built-in macOS say voice",
                s.provider
            );
            return Ok((Box::new(say), "macos-say".into()));
        }
    }
    Ok((selected, s.provider.clone()))
}

#[tauri::command]
pub fn tts_check(state: State<'_, AppState>) -> AppResult<TtsStatusResponse> {
    status_response(&state)
}

#[tauri::command]
pub fn tts_get_settings(state: State<'_, AppState>) -> AppResult<crate::db::TtsSettings> {
    state.db.get_tts_settings()
}

/// Sample sentence rendered with the provider that would actually speak,
/// so users can hear the configured voice (and the whole Master Voice
/// chain) without rendering an entire document.
const TEST_SENTENCE: &str =
    "This is how your ResearchAI voice sounds. Everything you hear was rendered on this machine.";

#[tauri::command]
pub async fn tts_test_voice(app: AppHandle) -> AppResult<crate::services::tts::TtsAudio> {
    tauri::async_runtime::spawn_blocking(move || {
        let state = app.state::<AppState>();
        let s = state.db.get_tts_settings()?;
        let (voice, effective) = effective_provider(
            &s,
            state.resource_dir.as_deref(),
            state.data_dir.join("exports"),
        )?;
        log::info!(
            target: "researchai::tts",
            "voice test requested via provider '{effective}'"
        );
        voice.render(TEST_SENTENCE, "voice-test")
    })
    .await
    .map_err(|e| AppError::msg(format!("Voice test failed to run: {e}")))?
}

/// Convert any audio file (WAV, AIFF, M4A, FLAC, …) to an MP3 beside it,
/// so every render — past or present — can end up as MP3. Returns the
/// converted file's metadata for the player.
#[tauri::command]
pub async fn tts_convert_to_mp3(path: String) -> AppResult<crate::services::tts::TtsAudio> {
    tauri::async_runtime::spawn_blocking(move || convert_to_mp3_inner(&path))
        .await
        .map_err(|e| AppError::msg(format!("MP3 conversion failed to run: {e}")))?
}

/// Validation + conversion, free of Tauri state so tests can drive it.
pub(crate) fn convert_to_mp3_inner(path: &str) -> AppResult<crate::services::tts::TtsAudio> {
    use crate::error::AppError as E;
    crate::services::path_validation::validate_audio_path(path, "the audio file")?;
    let src = std::path::Path::new(path);
    if !src.is_file() {
        return Err(E::msg(format!("Audio file not found: {path}")));
    }
    let ext = src
        .extension()
        .map(|e| e.to_string_lossy().to_lowercase())
        .unwrap_or_default();
    if ext == "mp3" {
        return Err(E::msg("That file is already an MP3 — nothing to convert."));
    }
    if !crate::services::transcription::ffmpeg_available() {
        return Err(E::msg(
            "MP3 conversion needs ffmpeg — install it (e.g. `brew install ffmpeg`) \
             and try again.",
        ));
    }
    let out_dir = src
        .parent()
        .ok_or_else(|| E::msg("That audio file has no parent directory."))?;
    log::info!(target: "researchai::tts", "converting '{path}' to MP3");
    let mp3 = crate::services::tts::transcode_to_mp3(src, out_dir)?;
    let bytes = std::fs::metadata(&mp3)?.len();
    let duration_ms = crate::services::transcription::ffprobe_duration_ms(&mp3)
        .or_else(|| {
            crate::services::tts::wav_duration_ms_from_header(&mp3)
                .ok()
                .flatten()
        })
        .unwrap_or(0);
    Ok(crate::services::tts::TtsAudio {
        path: mp3.to_string_lossy().into_owned(),
        format: "mp3".into(),
        bytes,
        duration_ms,
    })
}

#[tauri::command]
pub fn tts_save_settings(
    state: State<'_, AppState>,
    settings: crate::db::TtsSettings,
) -> AppResult<crate::db::TtsSettings> {
    let mut s = prepare_tts_settings(settings)?;
    if s.provider == "master-voice" {
        // Stage a managed copy so the voice survives the source file moving
        // (Downloads cleanup, external drive) and the transcript sidecar has
        // a writable home.
        s.master_ref_path = stage_master_voice(&s.master_ref_path, &state.data_dir.join("voices"))?;
    }
    state.db.save_tts_settings(&s)?;
    Ok(s)
}

/// Copy the picked reference recording into `<data>/voices/` (plus its
/// transcript sidecar, when present) and return the staged path. Picking
/// the staged file again is a no-op. Kept free of Tauri state for tests.
pub(crate) fn stage_master_voice(src: &str, voices_dir: &std::path::Path) -> AppResult<String> {
    use crate::error::AppError as E;
    let src_path = std::path::Path::new(src.trim());
    if !src_path.is_file() {
        return Err(E::msg(format!(
            "The master voice recording was not found at “{}” — pick an audio file with Browse…",
            src
        )));
    }
    let ext = src_path
        .extension()
        .map(|e| e.to_string_lossy().to_lowercase())
        .unwrap_or_else(|| "wav".into());
    let dest = voices_dir.join(format!("master-voice.{ext}"));
    if src_path != dest {
        std::fs::create_dir_all(voices_dir)?;
        std::fs::copy(src_path, &dest)?;
        // Carry the transcript sidecar so whisper is not re-run on the copy.
        let src_side = sidecar_for(src_path);
        let dest_side = sidecar_for(&dest);
        if src_side.is_file() && !dest_side.is_file() {
            let _ = std::fs::copy(&src_side, &dest_side);
        }
    }
    Ok(dest.to_string_lossy().into_owned())
}

/// `<file>.ref.txt` transcript sidecar (written by the render script).
fn sidecar_for(p: &std::path::Path) -> std::path::PathBuf {
    let mut name = p.file_name().unwrap_or_default().to_os_string();
    name.push(".ref.txt");
    p.with_file_name(name)
}

/// Normalize and validate saved TTS settings (kept free of Tauri state so
/// the guards above are unit-testable).
fn prepare_tts_settings(mut s: crate::db::TtsSettings) -> AppResult<crate::db::TtsSettings> {
    s.provider = match s.provider.as_str() {
        "macos-say" => "macos-say".into(),
        "master-voice" => "master-voice".into(),
        _ => "piper".into(),
    };
    s.piper_path = s.piper_path.trim().to_string();
    s.voice_model_path = s.voice_model_path.trim().to_string();
    s.macos_voice = s.macos_voice.trim().to_string();
    s.master_ref_path = s.master_ref_path.trim().to_string();
    s.speed = s.speed.clamp(0.5, 2.0);
    // Piper fields are only validated while Piper is the selected provider —
    // switching to the macOS voice must stay possible with stale paths set.
    if s.provider == "piper" {
        crate::services::path_validation::validate_binary_path(
            &s.piper_path,
            "piper",
            "install it (e.g. `brew install piper`) and point at the executable, e.g. \
             /opt/homebrew/bin/piper",
        )?;
        crate::services::path_validation::validate_model_path(
            &s.voice_model_path,
            "a Piper voice model",
            "onnx",
        )?;
    }
    // The Master Voice is defined by its reference recording: selecting it
    // without one (or with a non-audio path) fails fast with guidance.
    if s.provider == "master-voice" {
        if s.master_ref_path.is_empty() {
            return Err(AppError::msg(
                "The Master Voice needs a reference recording — pick one with Browse… \
                 (Voice output → Master voice), e.g. a 30-second sample of the voice to clone.",
            ));
        }
        crate::services::path_validation::validate_audio_path(
            &s.master_ref_path,
            "the master voice recording",
        )?;
    }
    Ok(s)
}

/// Result of one narration job (Phase 8).
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct NarrationResult {
    /// Absolute path of the rendered audio file.
    pub audio_path: String,
    /// "wav" or "mp3".
    pub format: String,
    pub bytes: u64,
    pub duration_ms: u64,
    /// Words in the spoken script.
    pub words: usize,
    /// Engine that generated the script ("read_aloud" | "llama.cpp" | …).
    pub engine: String,
}

impl NarrationResult {
    fn from_audio(
        audio: crate::services::tts::TtsAudio,
        words: usize,
        engine: String,
    ) -> Self {
        Self {
            audio_path: audio.path,
            format: audio.format,
            bytes: audio.bytes,
            duration_ms: audio.duration_ms,
            words,
            engine,
        }
    }
}

/// Speak a document aloud: reads the document's own text (light cleanup,
/// no AI). Works in No-AI mode.
#[tauri::command]
pub async fn tts_speak_document(
    app: AppHandle,
    document_id: String,
) -> AppResult<NarrationResult> {
    tauri::async_runtime::spawn_blocking(move || {
        let state = app.state::<AppState>();
        speak_document_inner(&state, &document_id)
    })
    .await
    .map_err(|e| AppError::msg(format!("Read-aloud failed to run: {e}")))?
}

fn speak_document_inner(state: &AppState, document_id: &str) -> AppResult<NarrationResult> {
    let s = state.db.get_tts_settings()?;
    let doc_text = state.db.get_document_text(document_id)?;
    if doc_text.trim().is_empty() {
        return Err(AppError::msg(
            "This document has no readable text yet — wait for indexing to finish.",
        ));
    }
    let title = state
        .db
        .get_document(document_id)
        .ok()
        .map(|d| d.title.unwrap_or_else(|| d.file_name))
        .unwrap_or_else(|| "document".into());

    let script = crate::services::narration::speakable(&doc_text);
    let words = script.split_whitespace().count();
    let hint = sanitize_hint(&title);
    let (voice, _) = effective_provider(&s, state.resource_dir.as_deref(), state.data_dir.join("exports"))?;
    let audio = voice.render(&script, &hint)?;
    Ok(NarrationResult::from_audio(audio, words, "read_aloud".into()))
}

/// Generate a spoken narration (summary or podcast) with the local model and
/// render it to audio. Hard-gated in No-AI mode (spec §35).
#[tauri::command]
pub async fn tts_narrate(
    app: AppHandle,
    document_id: String,
    kind: String,
) -> AppResult<NarrationResult> {
    tauri::async_runtime::spawn_blocking(move || {
        let state = app.state::<AppState>();

        if !state
            .settings
            .lock()
            .expect("settings lock")
            .ai_enabled
        {
            return Err(AppError::msg(
                "AI is disabled (No-AI mode). Summaries and podcast narration need the local \
                 model — read-aloud still works.",
            ));
        }

        let kind = crate::services::narration::NarrationKind::from_str(&kind)?;
        if matches!(kind, crate::services::narration::NarrationKind::ReadAloud) {
            return speak_document_inner(&state, &document_id);
        }

        // Script generation needs the local model: resolve + load on demand
        // (same flow as ai_ask, Phase 3).
        let ai = state.db.get_ai_settings()?;
        let model = resolve_model(&state.db, &ai)?;
        let binary = crate::services::bundled::resolve_llama_binary(
            &ai.llama_server_path,
            state.resource_dir.as_deref(),
        )?;
        if !matches!(
            state.llm_runtime.snapshot().state,
            crate::services::llm_runtime::LoadState::Ready { .. }
        ) {
            state.llm_runtime.ensure_loaded(
                &binary,
                std::path::Path::new(&model.file_path),
                &ai,
                std::time::Duration::from_secs(120),
            )?;
        }
        state.llm_runtime.touch();
        let snapshot = state.llm_runtime.snapshot();
        let port = match snapshot.state {
            crate::services::llm_runtime::LoadState::Ready { port } => port,
            crate::services::llm_runtime::LoadState::Failed { detail } => {
                return Err(AppError::msg(detail))
            }
            _ => return Err(AppError::msg("The local model is not ready yet.")),
        };
        let provider = crate::services::ai::LlamaCppProvider::new(
            &format!("http://127.0.0.1:{port}"),
            &model.file_name,
            None,
        );

        let doc_text = state.db.get_document_text(&document_id)?;
        if doc_text.trim().is_empty() {
            return Err(AppError::msg(
                "This document has no readable text yet — wait for indexing to finish.",
            ));
        }
        let title = state
            .db
            .get_document(&document_id)
            .ok()
            .map(|d| d.title.unwrap_or_else(|| d.file_name))
            .unwrap_or_else(|| "document".into());

        let script = crate::services::narration::build_script(kind, &title, &doc_text, &provider)?;
        let words = script.split_whitespace().count();
        let hint = sanitize_hint(&title);

        let tts = state.db.get_tts_settings()?;
        let (voice, _) = effective_provider(&tts, state.resource_dir.as_deref(), state.data_dir.join("exports"))?;
        let audio = voice.render(&script, &format!("{}-{hint}", kind_slug(kind)))?;
        Ok(NarrationResult::from_audio(
            audio,
            words,
            provider.name().to_string(),
        ))
    })
    .await
    .map_err(|e| AppError::msg(format!("Narration failed to run: {e}")))?
}

use crate::db::LocalModelRow;

fn resolve_model(db: &crate::db::Db, settings: &crate::db::AiSettings) -> AppResult<LocalModelRow> {
    let id = settings
        .active_model_id
        .as_deref()
        .ok_or_else(|| AppError::msg(
            "No local model is selected. Add a GGUF model in Settings → Local AI and choose one.",
        ))?;
    let model = db.get_local_model(id)?;
    if model.status != "available" {
        return Err(AppError::msg(format!(
            "The selected model file is not available on disk ({}). Re-scan or re-add it.",
            model.status
        )));
    }
    Ok(model)
}

fn sanitize_hint(title: &str) -> String {
    let cleaned: String = title
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect();
    let trimmed = cleaned.trim_matches('-').to_string();
    if trimmed.is_empty() {
        "doc".into()
    } else {
        trimmed.chars().take(40).collect()
    }
}

fn kind_slug(kind: crate::services::narration::NarrationKind) -> String {
    match kind {
        crate::services::narration::NarrationKind::ReadAloud => "read_aloud".into(),
        crate::services::narration::NarrationKind::Summary5 => "summary-5min".into(),
        crate::services::narration::NarrationKind::Summary10 => "summary-10min".into(),
        crate::services::narration::NarrationKind::Summary20 => "summary-20min".into(),
        crate::services::narration::NarrationKind::Podcast => "podcast".into(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Minimal valid PCM WAV (24 kHz mono 16-bit, `samples` frames).
    fn write_minimal_wav(dir: &std::path::Path, name: &str, samples: usize) -> std::path::PathBuf {
        let data: Vec<u8> = vec![0u8; samples * 2];
        let mut bytes: Vec<u8> = b"RIFF".to_vec();
        bytes.extend_from_slice(&(36 + data.len() as u32).to_le_bytes());
        bytes.extend_from_slice(b"WAVE");
        bytes.extend_from_slice(b"fmt ");
        bytes.extend_from_slice(&16u32.to_le_bytes());
        bytes.extend_from_slice(&1u16.to_le_bytes()); // PCM
        bytes.extend_from_slice(&1u16.to_le_bytes()); // mono
        bytes.extend_from_slice(&24_000u32.to_le_bytes());
        bytes.extend_from_slice(&48_000u32.to_le_bytes()); // byte rate
        bytes.extend_from_slice(&2u16.to_le_bytes()); // block align
        bytes.extend_from_slice(&16u16.to_le_bytes()); // bits
        bytes.extend_from_slice(b"data");
        bytes.extend_from_slice(&(data.len() as u32).to_le_bytes());
        bytes.extend_from_slice(&data);
        let path = dir.join(name);
        std::fs::write(&path, &bytes).unwrap();
        path
    }

    /// Missing files, non-audio paths and already-MP3 inputs fail with
    /// guidance before any subprocess runs.
    #[test]
    fn convert_to_mp3_rejects_bad_inputs() {
        let dir = crate::db::tests::TempDir::new_with_label("mp3-convert");

        let missing = convert_to_mp3_inner(&dir.path().join("gone.wav").to_string_lossy())
            .unwrap_err()
            .to_string();
        assert!(missing.contains("not found"), "got: {missing}");

        let txt = dir.path().join("notes.txt");
        std::fs::write(&txt, b"text").unwrap();
        let not_audio = convert_to_mp3_inner(&txt.to_string_lossy()).unwrap_err().to_string();
        assert!(not_audio.contains("does not look like"), "got: {not_audio}");

        let mp3 = dir.path().join("already.mp3");
        std::fs::write(&mp3, b"\xff\xfb\x90\x64").unwrap();
        let dup = convert_to_mp3_inner(&mp3.to_string_lossy()).unwrap_err().to_string();
        assert!(dup.contains("already an MP3"), "got: {dup}");
    }

    /// End-to-end when ffmpeg is installed (this machine): a real WAV in,
    /// a real MP3 beside it out — valid frame magic, non-zero duration from
    /// ffprobe, and the source file untouched. Skips only when the optional
    /// tool itself is absent (the command's own precondition).
    #[test]
    fn convert_to_mp3_produces_a_real_mp3_when_ffmpeg_exists() {
        if !crate::services::transcription::ffmpeg_available() {
            return;
        }
        let dir = crate::db::tests::TempDir::new_with_label("mp3-real");
        let wav = write_minimal_wav(dir.path(), "sample.wav", 12_000); // 0.5 s
        let out = convert_to_mp3_inner(&wav.to_string_lossy()).unwrap();

        assert_eq!(out.format, "mp3");
        assert!(out.path.ends_with("sample.mp3"), "{}", out.path);
        let bytes = std::fs::read(&out.path).unwrap();
        assert!(bytes.len() > 1000, "suspiciously small: {}", bytes.len());
        let magic_ok = bytes.starts_with(b"ID3")
            || (bytes[0] == 0xff && (bytes[1] & 0xe0) == 0xe0);
        assert!(magic_ok, "not an MP3 frame: {:02x?}", &bytes[..2.min(bytes.len())]);
        assert!(out.duration_ms >= 400, "duration: {}", out.duration_ms);
        // Non-destructive: the source WAV stays.
        assert!(wav.is_file());
    }

    /// Live harness for the Audio tab's "Convert to MP3" button: drives the
    /// exact function the `tts_convert_to_mp3` command runs, against a real
    /// machine file (e.g. a freshly finished document render).
    ///
    /// `RESEARCHAI_CONVERT=/path/to/audio.wav cargo test --lib \
    ///   live_convert_real_file -- --ignored`
    #[test]
    #[ignore = "live harness: set RESEARCHAI_CONVERT to a real audio file"]
    fn live_convert_real_file_to_mp3() {
        let path = std::env::var("RESEARCHAI_CONVERT")
            .expect("set RESEARCHAI_CONVERT to the audio file to convert");
        let out = convert_to_mp3_inner(&path).expect("conversion failed");
        assert_eq!(out.format, "mp3");
        assert!(out.path.ends_with(".mp3"), "{}", out.path);
        assert!(std::path::Path::new(&out.path).is_file());
        assert!(out.bytes > 1_000, "suspiciously small: {}", out.bytes);
        assert!(out.duration_ms > 0, "ffprobe returned no duration");
    }

    /// A fully configured Piper (binary + voice present) must stay selected.
    #[cfg(unix)]
    #[test]
    fn configured_piper_stays_piper() {
        use std::os::unix::fs::PermissionsExt as _;

        let dir = crate::db::tests::TempDir::new_with_label("tts-eff");
        let bin = dir.path().join("piper");
        std::fs::write(&bin, b"#!/bin/sh\nexit 0\n").unwrap();
        std::fs::set_permissions(&bin, std::fs::Permissions::from_mode(0o755)).unwrap();
        let model = dir.path().join("en_US-amy-medium.onnx");
        std::fs::write(&model, b"onnx").unwrap();

        let s = crate::db::TtsSettings {
            provider: "piper".into(),
            piper_path: bin.to_string_lossy().into_owned(),
            voice_model_path: model.to_string_lossy().into_owned(),
            ..crate::db::TtsSettings::default()
        };
        let (prov, id) = effective_provider(&s, None, dir.path().join("out")).unwrap();
        assert_eq!(id, "piper");
        assert!(prov.check().ready);
    }

    /// Unconfigured Piper on macOS falls back to the zero-install `say`
    /// voice so "Render audio" works out of the box.
    #[cfg(target_os = "macos")]
    #[test]
    fn unconfigured_piper_falls_back_to_the_macos_voice() {
        let dir = crate::db::tests::TempDir::new_with_label("tts-fb");
        let s = crate::db::TtsSettings {
            provider: "piper".into(),
            ..crate::db::TtsSettings::default()
        };
        let (prov, id) = effective_provider(&s, None, dir.path().join("out")).unwrap();
        if id != "macos-say" {
            // `say` unavailable in this environment — nothing to assert.
            return;
        }
        assert!(prov.check().ready);
    }

    /// Saving a recording as the piper binary is rejected with guidance
    /// instead of silently disabling audio generation.
    #[test]
    fn saving_an_audio_file_as_the_piper_binary_is_rejected() {
        let err = prepare_tts_settings(crate::db::TtsSettings {
            provider: "piper".into(),
            piper_path: "/Users/odere/Downloads/take_I.wav".into(),
            ..crate::db::TtsSettings::default()
        })
        .unwrap_err()
        .to_string();
        assert!(err.contains("audio/video file"), "got: {err}");
        assert!(err.contains("piper"), "got: {err}");
    }

    /// The same settings save cleanly once Piper is deselected — switching
    /// to the macOS voice must never be blocked by stale Piper paths.
    #[test]
    fn macos_say_selection_skips_piper_path_validation() {
        let saved = prepare_tts_settings(crate::db::TtsSettings {
            provider: "macos-say".into(),
            piper_path: "/Users/odere/Downloads/take_I.wav".into(),
            ..crate::db::TtsSettings::default()
        })
        .unwrap();
        assert_eq!(saved.provider, "macos-say");
    }

    /// Selecting the Master Voice without a reference recording is rejected
    /// with actionable guidance instead of silently rendering nothing.
    #[test]
    fn master_voice_without_a_recording_is_rejected() {
        let err = prepare_tts_settings(crate::db::TtsSettings {
            provider: "master-voice".into(),
            ..crate::db::TtsSettings::default()
        })
        .unwrap_err()
        .to_string();
        assert!(err.contains("reference recording"), "got: {err}");
        assert!(err.contains("Browse"), "got: {err}");
    }

    /// A non-audio path (the piper binary, say) is rejected for the master
    /// reference — the mirror image of the original audio-as-binary guard.
    #[test]
    fn master_voice_rejects_non_audio_paths() {
        let err = prepare_tts_settings(crate::db::TtsSettings {
            provider: "master-voice".into(),
            master_ref_path: "/opt/homebrew/bin/piper".into(),
            ..crate::db::TtsSettings::default()
        })
        .unwrap_err()
        .to_string();
        assert!(err.contains("does not look like"), "got: {err}");
    }

    /// An audio reference passes validation; stale Piper paths stay ignored.
    #[test]
    fn master_voice_accepts_an_audio_reference() {
        let saved = prepare_tts_settings(crate::db::TtsSettings {
            provider: "master-voice".into(),
            master_ref_path: "/Users/odere/Downloads/take_I.wav".into(),
            piper_path: "/stale/path".into(),
            ..crate::db::TtsSettings::default()
        })
        .unwrap();
        assert_eq!(saved.provider, "master-voice");
    }

    /// Saving copies the recording into the managed voices dir (so the
    /// voice survives the source file moving) and carries the transcript
    /// sidecar along. Re-saving the staged file is a no-op.
    #[test]
    fn staging_the_master_voice_copies_file_and_sidecar() {
        let dir = crate::db::tests::TempDir::new_with_label("tts-stage");
        let src = dir.path().join("take_I.wav");
        std::fs::write(&src, b"RIFFdummy").unwrap();
        std::fs::write(sidecar_for(&src), b"Somebody is in charge.").unwrap();
        let voices = dir.path().join("voices");

        let staged = stage_master_voice(&src.to_string_lossy(), &voices).unwrap();
        let staged_path = std::path::Path::new(&staged);
        assert!(staged_path.is_file(), "staged copy must exist: {staged}");
        assert!(staged.ends_with("master-voice.wav"), "{staged}");
        assert_eq!(
            std::fs::read_to_string(sidecar_for(staged_path)).unwrap(),
            "Somebody is in charge."
        );

        // Re-saving the staged path must not copy the file onto itself.
        let again = stage_master_voice(&staged, &voices).unwrap();
        assert_eq!(again, staged);

        // A vanished source is an actionable error, not a panic.
        let err = stage_master_voice("/no/such/recording.wav", &voices)
            .unwrap_err()
            .to_string();
        assert!(err.contains("not found"), "got: {err}");
    }

    /// Master Voice selected but unusable (no uv/recording on this machine)
    /// falls back like Piper does, so Render never dies silently.
    #[cfg(target_os = "macos")]
    #[test]
    fn unusable_master_voice_falls_back_to_a_working_voice() {
        let dir = crate::db::tests::TempDir::new_with_label("tts-mvfb");
        let s = crate::db::TtsSettings {
            provider: "master-voice".into(),
            master_ref_path: dir.path().join("missing.wav").to_string_lossy().into(),
            ..crate::db::TtsSettings::default()
        };
        let (prov, id) = effective_provider(&s, None, dir.path().join("out")).unwrap();
        if id == "master-voice" {
            // A fully configured Master Voice on this machine — nothing to prove.
            assert!(prov.check().ready);
            return;
        }
        assert!(prov.check().ready, "fallback '{id}' must actually render");
    }
}
